### ISSUE TITLE
Dashboard onbereikbaar

### ISSUE THREAD

**Issue by Jolandadane** [q-m/questionmark-dash#18]
Klopt het dat ons Dashboard 'not available' is? ik heb het over deze: http://192.168.250.207:3030/qm

**Comment by rvw** [comment]
Kan je alleen bereiken als je [op hetzelfde netwerk bent](https://nl.wikipedia.org/wiki/RFC_1918), dus op kantoor.

**Comment by Jolandadane** [comment]
Ah chips, stom. Dat is natuurlijk zo.
