### ISSUE TITLE
KPI' research toevoegen

### ISSUE THREAD

**Issue by Gustaaf** [q-m/questionmark-dash#20]
@wvengen Research zou graag twee KPI's toevoegen in het dashboard. Deze mogen in de plaats komen van 'Total products' en 'Total  barcodes'. 
1. Dekking Duurzaamheid, cijfer is te vinden op https://dbinsights.herokuapp.com/queries/4711
2. Dichtheid Informatie, cijfer is te vinden op https://dbinsights.herokuapp.com/queries/4703

**Comment by wvengen** [comment]
See also https://github.com/q-m/questionmark-web/issues/349.
